import PDFDocument from 'pdfkit';
import type { MedicineRow, VitalRow } from '../types';

interface ReportData {
  userName: string;
  adherenceRate: number;
  taken: number;
  missed: number;
  snoozed: number;
  medicines: MedicineRow[];
  vitals: VitalRow[];
  generatedAt: Date;
}

const BRAND_COLOR = '#2563eb';
const GRAY = '#6b7280';
const LIGHT_GRAY = '#f3f4f6';
const RED = '#ef4444';
const GREEN = '#22c55e';

export function generateHealthReportPDF(data: ReportData): PDFKit.PDFDocument {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  // ─── Header ────────────────────────────────────────────────────────────────
  doc.rect(0, 0, doc.page.width, 80).fill(BRAND_COLOR);
  doc
    .fillColor('#fff')
    .fontSize(22)
    .font('Helvetica-Bold')
    .text('MediTrack Health Report', 50, 25);
  doc
    .fontSize(10)
    .font('Helvetica')
    .text(`Generated on ${data.generatedAt.toLocaleDateString('en-US', { dateStyle: 'long' })}`, 50, 55);

  doc.moveDown(4);

  // ─── Patient Info ──────────────────────────────────────────────────────────
  doc.fillColor('#111827').fontSize(16).font('Helvetica-Bold').text('Patient Summary');
  doc.moveDown(0.3);
  doc.fillColor(GRAY).fontSize(11).font('Helvetica').text(`Name: ${data.userName}`);
  doc.moveDown(2);

  // ─── Adherence Overview ────────────────────────────────────────────────────
  sectionTitle(doc, 'Adherence Overview (Last 7 Days)');

  const rateColor = data.adherenceRate >= 80 ? GREEN : data.adherenceRate >= 50 ? '#f59e0b' : RED;

  doc
    .fillColor(rateColor)
    .fontSize(36)
    .font('Helvetica-Bold')
    .text(`${data.adherenceRate}%`, { align: 'center' });

  doc.fillColor(GRAY).fontSize(11).font('Helvetica').text('Adherence Rate', { align: 'center' });
  doc.moveDown(0.8);

  statsRow(doc, [
    { label: 'Doses Taken', value: String(data.taken), color: GREEN },
    { label: 'Doses Missed', value: String(data.missed), color: RED },
    { label: 'Snoozed', value: String(data.snoozed), color: '#f59e0b' },
  ]);

  doc.moveDown(2);

  // ─── Active Medicines ──────────────────────────────────────────────────────
  sectionTitle(doc, 'Active Medicines');
  const activeMeds = data.medicines.filter((m) => m.is_active);

  if (activeMeds.length === 0) {
    doc.fillColor(GRAY).fontSize(11).text('No active medicines.');
  } else {
    for (const med of activeMeds) {
      tableRow(doc, `${med.name} (${med.dosage})`, `${med.form} · ${med.frequency.replace(/_/g, ' ')} · ${(med.times as unknown as string[]).join(', ')}`);
    }
  }

  doc.moveDown(2);

  // ─── Vitals ────────────────────────────────────────────────────────────────
  sectionTitle(doc, 'Recent Vitals');

  if (data.vitals.length === 0) {
    doc.fillColor(GRAY).fontSize(11).text('No vitals logged.');
  } else {
    for (const vital of data.vitals) {
      const reading =
        vital.type === 'blood_pressure'
          ? `${vital.systolic}/${vital.diastolic} mmHg`
          : `${vital.value} ${vital.unit}`;
      const typeLabel = vital.type.replace(/_/g, ' ');
      const date = new Date(vital.logged_at).toLocaleDateString('en-US');
      tableRow(doc, `${typeLabel.charAt(0).toUpperCase() + typeLabel.slice(1)}`, `${reading} · ${date}`);
    }
  }

  // ─── Footer ────────────────────────────────────────────────────────────────
  doc
    .moveDown(3)
    .fontSize(9)
    .fillColor(GRAY)
    .text('This report is generated by MediTrack and is for personal health reference only.', {
      align: 'center',
    });

  doc.end();
  return doc;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function sectionTitle(doc: PDFKit.PDFDocument, title: string) {
  doc
    .fillColor(BRAND_COLOR)
    .fontSize(13)
    .font('Helvetica-Bold')
    .text(title);
  doc
    .moveTo(50, doc.y + 3)
    .lineTo(doc.page.width - 50, doc.y + 3)
    .strokeColor(BRAND_COLOR)
    .lineWidth(1)
    .stroke();
  doc.moveDown(0.8);
}

function statsRow(doc: PDFKit.PDFDocument, stats: { label: string; value: string; color: string }[]) {
  const colWidth = (doc.page.width - 100) / stats.length;
  const startX = 50;
  const y = doc.y;

  stats.forEach((stat, i) => {
    const x = startX + i * colWidth;
    doc
      .rect(x, y, colWidth - 8, 60)
      .fill(LIGHT_GRAY);
    doc
      .fillColor(stat.color)
      .fontSize(24)
      .font('Helvetica-Bold')
      .text(stat.value, x, y + 8, { width: colWidth - 8, align: 'center' });
    doc
      .fillColor(GRAY)
      .fontSize(10)
      .font('Helvetica')
      .text(stat.label, x, y + 38, { width: colWidth - 8, align: 'center' });
  });

  doc.y = y + 70;
}

function tableRow(doc: PDFKit.PDFDocument, left: string, right: string) {
  const y = doc.y;
  doc.rect(50, y, doc.page.width - 100, 28).fill(LIGHT_GRAY);
  doc
    .fillColor('#111827')
    .fontSize(11)
    .font('Helvetica-Bold')
    .text(left, 58, y + 8, { width: 220 });
  doc
    .fillColor(GRAY)
    .font('Helvetica')
    .text(right, 280, y + 8, { width: doc.page.width - 340 });
  doc.moveDown(0.6);
}
